Convert integration tests 2
alphagov/collections pull request #2326
Opened 2021-03-19 14:11 UTC by hannako

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

2021-03-23 09:31 UTC, hannako commented on spec/features/step_nav_page_spec.rb
> +    expect(page.has_css?(".gem-c-breadcrumbs")).to be
this is fixed in the convert commit

2021-03-23 21:49 UTC, sihugh requested changes
Just a few of the weird `.to be` conversions. Otherwise, all good

2021-03-23 21:49 UTC, sihugh commented on spec/features/world_wide_taxon_browsing_spec.rb
> +      expect(page.has_link?(content["title"])).to be
.to be

2021-03-23 21:49 UTC, sihugh commented on spec/features/world_wide_taxon_browsing_spec.rb
> +    expect(page.has_link?("Get emails for this topic")).to be
.to be

2021-03-23 21:49 UTC, sihugh commented on spec/features/transition_landing_page_spec.rb
> +feature "Transition landing page" do
RSpec.

2021-03-24 09:29 UTC, sihugh approved these changes
🎉

2021-03-24 09:42 UTC, sihugh approved these changes

2021-03-24 09:45 UTC, merged