Add additional sections for International Delegation pages
alphagov/collections pull request #3032
Opened 2022-11-07 16:43 UTC by brucebolt

International Delegation pages are a subtype of World Location News.

They include a number of additional sections, which are added into the page in this PR.

The style of some elements has changed slightly, as we move away from Whitehall's own rendering of components to properly using GOV.UK Publishing Components.

Additionally, Whitehall renders the incorrect crest for organisations that do not use the coat of arms, incorrectly uses the FCDO colour scheme for all organisations and links to FCDO on all organisation logos.  This is fixed in the Collections rendered version.

## Screenshots
| Collections  | Whitehall  |
|---|---|
| ![Screenshot showing an international delegation page rendered by Collections.  The logo crest for the Ministry of Defence is now correctly showing the MoD crest, rather than the coat of arms. ](https://user-images.githubusercontent.com/6329861/200557022-378b9cb6-95b3-45bd-b990-ea299c374bd0.png) | ![Screenshot showing the same international delegation page rendered by Whitehall.](https://user-images.githubusercontent.com/6329861/200552290-23f08a3f-9454-42d9-b6cf-52aa3d1f2183.png) |

This PR is dependent on https://github.com/alphagov/publishing-api/pull/2187 being merged and the Worldwide Organisation pages republished.

[Trello card](https://trello.com/c/SHpTX3sI/364-get-collections-to-render-additional-information-for-international-delegation-pages)

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

2022-11-10 13:31 UTC, JonathanHallam approved these changes
Happy with this, thanks, passing over to F&V

2022-11-11 15:41 UTC, chao-xian requested changes
See comment about the rendering. Would really not want this to be merged and deployed until that's looked into.

2022-11-15 11:45 UTC, JonathanHallam commented
> Hello. Although the code changes look ok, the page isn't rendering what I expected to see based on the screenshots and https://www.gov.uk/world/organisations/uk-joint-delegation-to-nato.
> 
> See https://collections-pr-3032.herokuapp.com/world/organisations/uk-joint-delegation-to-nato
> 
> ![Screenshot 2022-11-11 at 15 39 20](https://user-images.githubusercontent.com/424772/201374201-a2827afb-a6e3-4b20-b151-b93ce1cf7d05.png)

Spoke offline earlier about why I thought this was happening, turns out I was totally wrong. The link here is to a worldwide organisation not an international delegation. The changes can be seen on links like this gov.uk/world/uk-mission-to-the-wto-un-and-other-international-organisations-geneva

2022-11-17 14:08 UTC, JonathanHallam commented on app/views/world_location_news/show.html.erb
> +          <% contact.dig("details", "email_addresses").each do |email_address| %>
This line causes an error if there are no email addresses 

```
ActionView::Template::Error
undefined method `each' for nil:NilClass
/data/vhost/collections/releases/20221117112932/app/views/world_location_news/show.html.erb:197:in `block in _app_views_world_location_news_show_html_erb___1299014545407855788_83200'
/data/vhost/collections/releases/20221117112932/app/views/world_location_news/show.html.erb:176:in `each'
/data/vhost/collections/releases/20221117112932/app/views/world_location_news/s
```

2022-11-22 17:05 UTC, chao-xian approved these changes

2022-11-22 17:07 UTC, merged